### ISSUE TITLE
"sync" thread is hung at function feed_reader_utils_UTF8fix in Utils.vala:117 with string "And we\031re almost home&"

### ISSUE THREAD

**Issue by Raulvo** [jangernert/FeedReader#733]
During the GDB session I have seen that FeedReader creates threads while parsing the feeds. Thread 25 never exits and is in what to me seems an infinite loop within vilistextum trying to convert the string "And we\031re almost home&". FeedReader GUI remains in syncing state but there is no progress.

List of threads and backtrace of the hung thread:

```
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7f8cac0 (LWP 10271) "feedreader" 0x00007ffff72e5bf9 in __GI___poll (fds=0x555555e9d7d0, nfds=4, timeout=9082) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7fffe0c2e700 (LWP 10275) "feedreader" 0x00007ffff0ec69f3 in futex_wait_cancelable (private=<optimised out>, expected=0, 
    futex_word=0x7fffea9dc1e0 <bmalloc::SafePerProcessStorageTraits<bmalloc::Scavenger>::Storage::s_memory+64>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fffdfda3700 (LWP 10276) "gmain" 0x00007ffff72e5bf9 in __GI___poll (fds=0x5555557bd890, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7fffdf5a2700 (LWP 10277) "gdbus" 0x00007ffff72e5bf9 in __GI___poll (fds=0x7fff7c001610, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7fffdeb94700 (LWP 10278) "dconf worker" 0x00007ffff72e5bf9 in __GI___poll (fds=0x555555a15870, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7fffdccff700 (LWP 10279) "StorageManager" 0x00007ffff72e5bf9 in __GI___poll (fds=0x7fff88002650, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7fff8fffd700 (LWP 10280) "ebsiteDataStore" 0x00007ffff72e5bf9 in __GI___poll (fds=0x7fff80002f10, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  8    Thread 0x7fff879ff700 (LWP 10285) "PressureMonitor" 0x00007ffff0ec6f85 in futex_abstimed_wait_cancelable (private=<optimised out>, abstime=0x7fff879fe7e0, expected=0, 
    futex_word=0x7fffdcdd8060) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
* 25   Thread 0x7fff6f7f6700 (LWP 10322) "sync" __gconv_open (toset=toset@entry=0x7fff6f7d4b90 "UTF-8//", fromset=fromset@entry=0x7fff6f7d4b70 "UTF-8//", 
    handle=handle@entry=0x7fff6f7d4bc0, flags=flags@entry=0) at gconv_open.c:109
(gdb) thread 25
[Switching to thread 25 (Thread 0x7fff6f7f6700 (LWP 10322))]
#0  __gconv_open (toset=toset@entry=0x7fff6f7d4b90 "UTF-8//", fromset=fromset@entry=0x7fff6f7d4b70 "UTF-8//", handle=handle@entry=0x7fff6f7d4bc0, flags=flags@entry=0)
    at gconv_open.c:109
109	in gconv_open.c
(gdb) bt
#0  0x00007ffff71f363f in __gconv_open (toset=toset@entry=0x7fff6f7d4b90 "UTF-8//", fromset=fromset@entry=0x7fff6f7d4b70 "UTF-8//", handle=handle@entry=0x7fff6f7d4bc0, flags=flags@entry=0) at gconv_open.c:109
#1  0x00007ffff71f315e in iconv_open (tocode=0x7fff6f7d4b90 "UTF-8//", fromcode=0x7fff6f7d4b70 "UTF-8//") at iconv_open.c:71
#2  0x00007ffff7aada11 in read_char () at ../libraries/libVilistextum/fileio.c:144
#3  0x00007ffff7aae43f in html (extractText=0) at ../libraries/libVilistextum/html.c:230
#4  0x00007ffff7aad25f in vilistextum (text=0x7fff32276320 "And we\031re almost home&", extractText=0) at ../libraries/libVilistextum/vilistextum.c:55
#5  0x00007ffff7a4bd2f in feed_reader_utils_UTF8fix (old_string=0x7fff32276320 "And we\031re almost home&", removeHTML=0)
    at /home/user/soft/src/FeedReader/src/Utils.vala:117
#6  0x00007ffff7a7c75f in feed_reader_data_base_write_articles (self=0x7fffd0018b20, articles=0x5555560cea70)
    at /home/user/soft/src/FeedReader/src/DataBaseWriteAccess.vala:500
#7  0x00007fffdc2d54c0 in feed_reader_local_interface_real_getArticles (base=0x555555bd76e0, count=400, whatToGet=FEED_READER_ARTICLE_STATUS_ALL, since=0x555555b82c60, feedID=0x0, isTagID=0, cancellable=0x0) at /home/user/soft/src/FeedReader/plugins/backend/local/localInterface.vala:685
#8  0x00007ffff7a8f1fc in feed_reader_feed_server_interface_getArticles (self=0x555555bd76e0, count=400, whatToGet=FEED_READER_ARTICLE_STATUS_ALL, since=0x555555b82c60, feedID=0x0, isTagID=0, cancellable=0x0) at /home/user/soft/src/FeedReader/src/Backend/FeedServerInterface.vala:111
#9  0x00007ffff7a8ddd8 in feed_reader_feed_server_getArticles (self=0x555555bd8dc0, count=400, whatToGet=FEED_READER_ARTICLE_STATUS_ALL, since=0x555555b82c60, feedID=0x0, isTagID=0, cancellable=0x7fffd00184b0) at /home/user/soft/src/FeedReader/src/Backend/FeedServer.vala:1013
#10 0x00007ffff7a85cff in feed_reader_feed_server_syncContent (self=0x555555bd8dc0, cancellable=0x7fffd00184b0)
    at /home/user/soft/src/FeedReader/src/Backend/FeedServer.vala:254
#11 0x00007ffff7a6c282 in feed_reader_feed_reader_backend_sync (self=0x555555bd8d20, initSync=0, cancellable=0x7fffd00184b0)
    at /home/user/soft/src/FeedReader/src/Backend/Backend.vala:230
#12 0x00007ffff7a6b386 in __lambda12_ (_data64_=0x555555bc6f60) at /home/user/soft/src/FeedReader/src/Backend/Backend.vala:95
#13 0x00007ffff7a6b3a1 in ___lambda12__feed_reader_feed_reader_backendasync_payload (self=0x555555bc6f60) at /home/user/soft/src/FeedReader/src/Backend/Backend.vala:95
#14 0x00007ffff7a74d96 in __lambda16_ (_data81_=0x7fff78009280) at /home/user/soft/src/FeedReader/src/Backend/Backend.vala:779
#15 0x00007ffff7a74e1d in ___lambda16__gthread_func (self=0x7fff78009280) at Backend.c:8134
#16 0x00007ffff6f2ee05 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff0ec06db in start_thread (arg=0x7fff6f7f6700) at pthread_create.c:463
#18 0x00007ffff72f288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Raulvo** [comment]
The feed causing the problem is this one: https://valdyas.org/fading/feed/
Blog entry: https://valdyas.org/fading/kde/and-were-almost-home/

**Comment by brendanlong** [comment]
Can you try the latest commit on master? I think this should be fixed by #736 (specifically 04a054f722b9e29d2b873d0f277e42b57d9a055a should have fixed strings that end in & or <)

**Comment by bilelmoussaoui** [comment]
A new flatpak version should be available soon. Please try that and let us know if you still have this issue

**Comment by Raulvo** [comment]
I have not been able to reproduce the bug again. I suppose it has been solved.

**Comment by brendanlong** [comment]
I created #741 to track that. Thanks!
