### ISSUE TITLE
Crash on Ubuntu 18.10 (OpenSSL-related?)

### ISSUE THREAD

**Issue by raczkow** [jangernert/FeedReader#800]
I'm trying to run FeedReader on Ubuntu 18.10 (building in my private PPA) with Nextcloud News backend. It crashes since 2.3.0. When I remove ~/.local/share/feedreader and try to start it, it works until I press sync button:

```
feedreader-INFO: 14:24:15.849: backend: sync started
(feedreader:28791): dconf-DEBUG: 14:24:15.849: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.849: change_notify: /org/gnome/feedreader/saved-state/currently-updating
(feedreader:28791): dconf-DEBUG: 14:24:15.849: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:15.854: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.854: change_notify: /org/gnome/feedreader/saved-state/window-width
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/window-height
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/window-maximized
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/expanded-categories
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/feed-row-scrollpos
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/feedlist-selected-row
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/feed-row-width
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/feeds-and-articles-width
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/articlelist-scrollpos
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/articlelist-selected-row
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/articlelist-top-row
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/show-articles
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/search-term
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:15.855: change_notify: /org/gnome/feedreader/saved-state/articleview-scrollpos
(feedreader:28791): dconf-DEBUG: 14:24:15.984: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)
(feedreader:28791): dconf-DEBUG: 14:24:15.985: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:16.124: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)
(feedreader:28791): dconf-DEBUG: 14:24:16.124: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:16.124: change_notify: /org/gnome/feedreader/saved-state/sync-status
(feedreader:28791): dconf-DEBUG: 14:24:16.124: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:16.260: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)
(feedreader:28791): dconf-DEBUG: 14:24:16.260: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:16.481: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)
(feedreader:28791): dconf-DEBUG: 14:24:16.484: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:16.610: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)
(feedreader:28791): dconf-DEBUG: 14:24:16.611: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
(feedreader:28791): dconf-DEBUG: 14:24:16.738: unwatch_fast: "/org/gnome/feedreader/tweaks/" (active: 2, establishing: 0)

(feedreader:28791): feedreader-WARNING **: 14:24:16.745: DataBase: Deleting nonexisting categories

(feedreader:28791): feedreader-WARNING **: 14:24:16.750: DataBase: Deleting articles without feed

(feedreader:28791): feedreader-WARNING **: 14:24:16.750: DataBase: Deleting unsubscribed feeds

(feedreader:28791): feedreader-WARNING **: 14:24:16.750: DataBase: Deleting nonexisting tags
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_notify: /org/gnome/feedreader/saved-state/expanded-categories
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_notify: /org/gnome/feedreader/saved-state/feedlist-selected-row
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_notify: /org/gnome/feedreader/saved-state/feed-row-scrollpos
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_fast
(feedreader:28791): dconf-DEBUG: 14:24:16.751: change_notify: /org/gnome/feedreader/saved-state/sync-status
(feedreader:28791): dconf-DEBUG: 14:24:16.752: watch_fast: "/org/gnome/feedreader/tweaks/" (establishing: 0, active: 1)
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?
```

**Comment by brendanlong** [comment]
Would it be possible for you to using gdb and then send us the backtrace? Unfortunately the logs aren't tell us where the problem happened.

I think you should be able to just run:

```
gdb feedreader
```

Then at the prompt type "run", and then when it crashes type "bt".

If possible, doing a build from source will also give a better backtrace since your PPA seems to be built in release mode (the `Note: no file path and line numbers can be retrieved`). I think the backtrace may be useful either way, but I'll be able to fix this much faster with a debug backtrace.

Thanks!

**Comment by brendanlong** [comment]
And just to be clear -- you've been seeing this bug since 2.3.0, but you're on the latest version now right? (git master or v2.5.1)

**Comment by raczkow** [comment]
[code]
#0  0x00007fff99b0f343 in nettle_memxor () from /usr/lib/x86_64-linux-gnu/libnettle.so.6
#1  0x00007fff99e8faa0 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#2  0x00007fff99e8bf3c in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#3  0x00007fff99e95cc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#4  0x00007fff99e97c28 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#5  0x00007fff99ed8190 in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#6  0x00007fff99ed82be in gnutls_session_key_update () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#7  0x00007fffe841a54f in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#8  0x00007fffe841ab36 in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#9  0x00007ffff7c7fc03 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff7e0aad3 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7e0a135 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff31fd164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#13 0x00007ffff76c7def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
[/code]

2.3.0 on Ubuntu 18.04 works ok.
2.3.0 on Ubuntu 18.10 crashes.
2.4.1 on Ubuntu 18.10 crashes.
2.5.0 on Ubuntu 18.10 crashes

**Comment by raczkow** [comment]
2.5.1 on Ubuntu 18.10 still crashes.

**Comment by raczkow** [comment]
2.6.1 on Ubuntu 18.10 crashes
2.6.1 on Ubuntu 18.04 works OK

Maybe it is an issue with openssl 1.1.1?

**Comment by brendanlong** [comment]
I'd like to help with this but I don't really know where to start. A crash in OpenSSL sounds like you're probably seeing a bug in OpenSSL, libsoup, or WebKitGTK. We never call OpenSSL directly :\

Is it possible that your PPA is building using a different version of OpenSSL than your local machine? Does FeedReader work if you clone our git repo and build it locally, or install the Flatpak from Flathub?

(Installing from Flathub in particular might help, since that should bundle a known-working version of OpenSSL)

**Comment by raczkow** [comment]
Funny story :-)
I've tried every new version which you released. 2.7.1 was crushing but today I opened it again and it started to work !!!!

**Comment by brendanlong** [comment]
Woo!
